//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Security.Framework.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al autenticar token, no se pudo obtener.
        /// </summary>
        internal static string ErrorAuthTokenNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorAuthTokenNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al almacenar certificado de cliente : .
        /// </summary>
        internal static string GuardarCertificadoClienteError {
            get {
                return ResourceManager.GetString("GuardarCertificadoClienteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El hashing de origen no coincide con el del mensaje descifrado.
        /// </summary>
        internal static string HasingEntrada {
            get {
                return ResourceManager.GetString("HasingEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machine-signature.
        /// </summary>
        internal static string Header_MACHINE_AUTHENTICATION {
            get {
                return ResourceManager.GetString("Header_MACHINE_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-app-signature.
        /// </summary>
        internal static string Header_X_APP_SIGNATURE {
            get {
                return ResourceManager.GetString("Header_X_APP_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores invalidos .
        /// </summary>
        internal static string InvalidArgumentException {
            get {
                return ResourceManager.GetString("InvalidArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede leer el mensaje de entrada..
        /// </summary>
        internal static string MensajeEntrada {
            get {
                return ResourceManager.GetString("MensajeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra autorizado para acceder a la informacion : .
        /// </summary>
        internal static string NoAutorizado {
            get {
                return ResourceManager.GetString("NoAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores nulos (null).
        /// </summary>
        internal static string NullableArgumentException {
            get {
                return ResourceManager.GetString("NullableArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaCertificadosServidorPrivado.
        /// </summary>
        internal static string ParamCertPrivServ {
            get {
                return ResourceManager.GetString("ParamCertPrivServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaCertificadosPublicosCliente.
        /// </summary>
        internal static string ParamCertPublicoCliente {
            get {
                return ResourceManager.GetString("ParamCertPublicoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaCertificadosServidorPublico.
        /// </summary>
        internal static string ParamCertPublicoServ {
            get {
                return ResourceManager.GetString("ParamCertPublicoServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassphraseCertificadoPrivadoServidor.
        /// </summary>
        internal static string ParamPassphraseCertPrivServ {
            get {
                return ResourceManager.GetString("ParamPassphraseCertPrivServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaArchivoDecripcion.
        /// </summary>
        internal static string ParamRutaMensajeDecriptado {
            get {
                return ResourceManager.GetString("ParamRutaMensajeDecriptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RutaArchivoEncripcion.
        /// </summary>
        internal static string ParamRutaMensajeEncriptado {
            get {
                return ResourceManager.GetString("ParamRutaMensajeEncriptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de la Url es invalido o Nulo.
        /// </summary>
        internal static string SEC_InvalidHostURI {
            get {
                return ResourceManager.GetString("SEC_InvalidHostURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.Framework.
        /// </summary>
        internal static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
    }
}
